### ISSUE TITLE
prepared statement "_pg3_0" already exists

### ISSUE THREAD

**Issue by gameveloster** [procrastinate-org/procrastinate#1074]
My worker process will crash after completing a task, throwing the error

```bash
2024-06-16 10:18:22 - ERROR - Main coroutine error, initiating remaining coroutines stop. Cause: ConnectorException('\n    Database error.\n    ')
2024-06-16 10:18:22 - INFO - Stop requested
2024-06-16 10:18:22 - ERROR - single_worker error: ConnectorException('\n    Database error.\n    ')
NoneType: None
prepared statement "_pg3_0" already exists
Database error.
One of the specified coroutines ended with an exception
```

Worker is started with the command

```
PYTHONPATH=. procrastinate --verbose --app=foo.tasks.app worker -q bar
```

This is my worker task:

```py
import logging
import procrastinate
from foo.config import DB_INFO

logger = logging.getLogger("Worker")

app = procrastinate.App(
    connector=procrastinate.PsycopgConnector(
        kwargs={**DB_INFO}
    )
)

@app.task(name="mytask", queue="myqueue")
def my_task(user_id):
    logger.info(f"Processing task for {user_id}")

if __name__ == "__main__":
    app.run_worker()
```

My installed pip packages are:
```
procrastinate     2.3.0
psycopg           3.1.19
psycopg-binary    3.1.19
psycopg-pool      3.2.2
psycopg2-binary   2.9.9
```

and Postgres DB is hosted on Supabase.

Healthcheck passses:
```
App configuration: OK
DB connection: OK
Found procrastinate_jobs table: OK
```

Any suggestions? Thanks

**Comment by ewjoachim** [comment]
Seems to be linked to [Psycopg's prepared statements](https://www.psycopg.org/psycopg3/docs/advanced/prepare.html#prepared-statements) features. Supabase mention they use a [connection pooler](https://supabase.com/docs/guides/database/connecting-to-postgres) (as far as I can tell), so I think the warning from the psycopg doc applies:

> [!WARNING]  
> Unless a connection pooling middleware explicitly declares otherwise, they are not compatible with prepared statements, because the same client connection may change the server session it refers to. If such middleware is used you should disable prepared statements, by setting the [Connection.prepare_threshold](https://www.psycopg.org/psycopg3/docs/api/connections.html#psycopg.Connection.prepare_threshold) attribute to None.

**Comment by aleksandr-shtaub** [comment]
To disable prepared statements refer to this example:

```python
PsycopgConnector(
    kwargs={
        "prepare_threshold": None
    }
)
```

You must have psycopg version [3.1][0] or higher to use this.

For more details, see [`psycopg_pool.ConnectionPool.kwargs`][1] and
[`psycopg.Connection.connect(..., prepare_threshold: int | None)`][2].

Unfortunately, passing `configure(connection)` callback to `PsycopgConnector` won't do it fully, because `listen_notify` doesn't obtain connection from a pool; instead, it connects manually:

https://github.com/procrastinate-org/procrastinate/blob/608c2cbdb9ea86a8a8d380f81caf41eb51692fd4/procrastinate/psycopg_connector.py#L240-L242

[0]: https://github.com/psycopg/psycopg/releases/tag/3.1
[1]: https://www.psycopg.org/psycopg3/docs/api/pool.html#psycopg_pool.ConnectionPool:~:text=kwargs%20(dict)%20%E2%80%93%20Extra%20arguments%20to%20pass%20to%20connect().%20Note%20that%20this%20is%20one%20dict%20argument%20of%20the%20pool%20constructor%2C%20which%20is%20expanded%20as%20connect()%20keyword%20parameters
[2]: https://www.psycopg.org/psycopg3/docs/api/connections.html#psycopg.Connection:~:text=prepare_threshold%20%E2%80%93%20Initial%20value%20for%20the%20prepare_threshold%20attribute%20of%20the%20connection%20(new%20in%20Psycopg%203.1).

**Comment by ewjoachim** [comment]
It looks like we should do something. I see 2 paths:
- Calling configure ourselves on the connection we create for `listen_notify`
- Documenting what needs to be done in that case.

@aleksandr-shtaub would you be interested in doing either ?
