### ISSUE TITLE
Allow to change the priority when retrying

### ISSUE THREAD

**Issue by medihack** [procrastinate-org/procrastinate#1096]
A nice additional feature would be to change the priority when retrying a job. For example, I would like to slightly increase the priority when a job fails and will be retried. Maybe we could use an additional parameter like `RetryStrategy(change_priority=2)` to increase it by 2.

**Comment by ewjoachim** [comment]
It makes sense!

I'm not sure about the API you suggested: change is implying add and it's a bit weird.

What about either
`RetryStrategy(priority_increment=2)`
Or
`RetryStrategy(update_priority=lambda attempts: 5+2*attempts)`
?

**Comment by medihack** [comment]
Yes, I really like the lambda usage. How about `RetryStrategy(update_priority=lambda job: 5+2*job.attempts)`? With access to the job, it's even possible to get the current priority.

**Comment by ewjoachim** [comment]
Ok !

**Comment by ewjoachim** [comment]
Hm, what about doing it a step further:
```python
@dataclasses.dataclass
class RetryDecision:
    should_retry: bool
    new_priority: int | None = None
    wait: float | None = None
```

We could decide that `RetryStrategy` subclasses should return a RetryDecision object to a new method (we'd implement backwards compat on `get_schedule_in` but it seems doable). The new method would recieve the job.

People would be able to implement their RetryStrategy subclass to achive what you're proposing.

Also, I'm very ok with the RetryStrategy class accepting a callable so that one may implement their strategy by passing a function as an argument rather than doing a whole subclass for overriding just one method.

I think we may be able to do all that without breaking existing code.

**Comment by ewjoachim** [comment]
(the main feature I see is that it will make adding other retry-related features less breaking and more cohesive in the future)

**Comment by medihack** [comment]
Yes, that sounds good. Should we just name the additional method ´def get_retry_decision(self, job: Job) -> RetryDecision | None`? 

```python
class RandomRetryStrategy(procrastinate.BaseRetryStrategy):
    def get_retry_decision(self, *, exception: Exception, job: Job, **kwargs) -> RetryDicision | None:
        ...
```

For compatibility reasons, we can call `get_retry_decision` first. If it's `None` (the default), we can call `get_schedule_in` as usual. But maybe we should depreciate `get_schedule_in` in the long run (to have only one API for that in a possible 3.x release).

**Comment by ewjoachim** [comment]
Fine by me.
Do we issue a PendingDeprecationWarning or a DeprecatedWarning directly ? I'd say the second as I guess the next change we'll do is drop it.
