### ISSUE TITLE
Support for dynamic creation of periodic tasks

### ISSUE THREAD

**Issue by benjamb** [procrastinate-org/procrastinate#564]
I'm looking to build a service where users may submit tasks to be run periodically.

Having attempted to use `PeriodicDeferrer`'s `register_task()` to no avail, I realised it's the workers that are ultimately responsible for managing periodic tasks, and will only end up picking up those it can discover at startup.

Hopefully I'm not barking up the wrong tree here.

**Comment by ewjoachim** [comment]
Yeah, periodic tasks for each worker are managed by each worker. They've been designed so far to have the worker read the tasks at import time and the list to stay stable during the worker's lifetime.

I'm not saying you couldn't make it work, though you might feel like you're fighting against the intended design. I don't really know if you should or shouldn't do it. I may be able to help you do it but I'm not entirely sure it makes sense to rewrite procrastinate to make this easier.

What I can tell you is, if I follow the approach you mention:
- You'll need each and every worker to know about the task to execute, and you'll need each and every worker to execute the `app.periodic` decorator, or the underlying `register_task`. For example, each worker could schedule a periodic task for itself using a system of queue where each worker has a dedicated queue. In this periodic task, each worker would read e.g. your SQL table that contains the tasks the users requested, and register the missing ones. Note that this will mean having the `PeriodicDeferer` introspect its own tasks in your code, and I don't think the `PeriodicDeferer`'s API is meant to be public, so in the future, we may be less careful about changing it that we would for the parts we documented.
- And I don't think we have planned anything in case a task needs to be de-scheduled.

That say there is another possibility which I believe will be much easier.

- When users schedule tasks, write this in an SQL table
- Have a single normal periodic task that runs as frequently as the most frequent setting your users can schedule tasks to (e.g. 1/min if that's the most often they can do it). On each run, the periodic task you implement will read your SQL table, determine if something needs to be run for the received timestamp, defer corresponding tasks and that's it.

The existing system already ensures that periodic tasks will run only once even if you have multiple workers.
If you do that, instead of trying to change the way procrastinate itself work, you're placing your code as a "procrastinate user" and separate responsibilities beter between what the lib does and what your particular project does.

**Comment by ewjoachim** [comment]
I'm going to close this ticket. Please repoen if I missed something.
