### ISSUE TITLE
Is it possible to "reload" a workers tasks?

### ISSUE THREAD

**Issue by bmarsh9** [procrastinate-org/procrastinate#799]
Just a general question on if it is possible to reload the tasks of a worker. For example, I'd like to see if the following is possible:

1. Define 5 tasks
2. Start a worker
3. (While worker is still running) Create a new task in the same import_path
4. Defer the new task and the worker (never restarted) executes it (currently I get the TaskNotFound exception)

Currently I'm running the workers in a separate docker container and so when I update the tasks I just restart all of the containers, which works fine but isn't ideal.

Thanks !

**Comment by ewjoachim** [comment]
I'm not sure it's a good idea to add more dark magic around imports than there already is. I think it makes more sense to link have our mental model say that 1 process == 1 version of the code.

Especially: if you run the the workers in docker, the sane way to have this is to have the code you run on live in the image (vs in a bind mount) so if you want to change the code, you'll want to redeploy a new image anyway. I'm not sure I love the idea of adding complexity in procrastinate to support you code not being immutable, because I'm not sure I identify this as a good practice.

Ok for you ?

**Comment by bmarsh9** [comment]
I wasn't really asking for "dark magic" or even any changes. I was just wondering if a worker could refresh functions from the import paths. Thanks

**Comment by ewjoachim** [comment]
Ah, I thought you meant that as a feature request.

You can always define a task that runs [importlib.reload](https://docs.python.org/3/library/importlib.html#importlib.reload). But there's nothing built in procrastinate to run a task once on every worker, so I'd guess you would need to define a specific branch that each worker alone listens to, and defer a reload task in each of those branches. This means your runtime may need to guess or introspect your deployment specifics (to know how many tasks to defer, and on which branch)
