### ISSUE TITLE
Error: No module named on procrastinate --app

### ISSUE THREAD

**Issue by zN3utr4l** [procrastinate-org/procrastinate#821]
I'm looking for a Celery replacement library on Windows, but one that doesn't use Rabbitmq or Redis.
I noticed that you have "support" for django, I was doing some tests but the worker still won't start.

![image](https://github.com/procrastinate-org/procrastinate/assets/73225008/f4583d7a-5cd6-4216-8289-7f2586dfc40f)

![image](https://github.com/procrastinate-org/procrastinate/assets/73225008/7e3c1647-1e3d-4e0b-b135-b6c913f28e3e)

![image](https://github.com/procrastinate-org/procrastinate/assets/73225008/0cb15702-f2d3-440b-ba50-e5ad487a9d3a)

**Comment by ewjoachim** [comment]
I think the keyword here may be `Windows`. We don't have a great track record of supporting Windows and I don't have an easy way to reproduce issues... I'm afraid I may be of limited help here :/

**Comment by ewjoachim** [comment]
Rereading your issue, I guess it's the same cause as what mandated this PR: https://github.com/procrastinate-org/procrastinate/pull/120

I guess the fix didn't work for you, so I guess exporting env vars isn't done the same way with your shell. I don't know if you're using cmd or powershell or bash through WSL. I hope that this will give you enough info to find what the actual issue is

**Comment by zN3utr4l** [comment]
thanks, I use powershell.

**Comment by ewjoachim** [comment]
https://github.com/procrastinate-org/procrastinate/issues/821

**Comment by ewjoachim** [comment]
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.3#using-the-variable-syntax
