### ISSUE TITLE
Bug(Sphinx): Autodoc fails to document wrapped functions

### ISSUE THREAD

**Issue by JacobCoffee** [procrastinate-org/procrastinate#865]
Hello, we are using Procrastinate for a work project and I'm having a difficult time getting wrapped functions to document with Sphinx correctly.

## Issue

When wrapping a function it fails to document.

For example 
```py
from somewhere import procrastinate_app as pa

@pa.periodic(cron="*/30 * * * *")  # type: ignore[misc]
@pa.task()  # type: ignore[misc]
async def sync_thing(**kwargs: Any) -> list[Thing] | Message:
    """Do thing

    Args:
        **kwargs: Keyword arguments passed to the task.
            These include ``timestamp`` from Procrastinate.

    Returns:
        Message: A message.
    """
    return await fetch_testboxes()
 ```
Will generate nothing for Sphinx's `autodoc`
```rst

API Reference
-------------

.. automodule:: path.to.module.tasks
    :members:
```

I think possibly related to https://github.com/sphinx-doc/sphinx/issues/3783, but I'm wondering if it can be fixed from your side.

**Comment by JacobCoffee** [comment]
Sure - I quite like the project. It may be a little bit before I can get to it though.

**Comment by ewjoachim** [comment]
Still interested in taking this ? :)

**Comment by ewjoachim** [comment]
Ok, qualifying the issue a bit better. I thought something was happening and it's actually very different.

The issue is not linked to `@periodic` but `@task`. The problem is that `@task` transforms the decorated function into a `procrastinate.Task`. And tasks are not function, so autodoc has no idea how to document it.

I _think_ (emphasis) we can actually do it the right way:
- Create a [mini sphinx extension](https://www.sphinx-doc.org/en/master/development/tutorials/autodoc_ext.html)
- that calls [`app.add_autodocumenter()`](https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_autodocumenter)
- to add a `TaskDocumenter`
- That inherits the normal [FunctionDocumenter](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/autodoc/__init__.py#L1272)
- And overrides `can_document_member`
- Implementation being `return isinstance(member, procrastinate.tasks.Task)`
- (plus add the `extra` dependency to sphinx
- ... and associated doc
- ... and if possible, a test, but I don't know how hard that might be)

**Comment by ewjoachim** [comment]
Bumping the ticket difficulty, this is not a oneliner anymore, sorry :D

Still interested, @JacobCoffee ? (you don't have to say yes just because of your previous answer, this ticket just became much more difficult and longer)

**Comment by JacobCoffee** [comment]
Thanks! :D super sorry for the delay :\ I started a new job and i've just been heads down 😓

**Comment by ewjoachim** [comment]
Nah, don't worry, it's ok :) Thanks for reporting the problem !
